name: EusTerminal
version: ${project.version}
main: cc.eumc.eusterminal.EusTerminal
api-version: 1.13
authors: [EucalyptusLeaves]
commands:
  _exec:
    permission: "eusterminal.exec"
  _download:
    permission: "eusterminal.download"